[package]
name = "wallgdm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
thiserror = "2.0.17"
image = "0.25.9"
quick-xml = "0.38.4"
colored = "3.0.0"
indicatif = "0.18.3"
serde = { version = "1.0.228", features = ["derive"] }
walkdir = "2.5.0"
dirs = "6.0.0"

[dev-dependencies]
tempfile = "3.24.0"
