//! Compile GNOME Shell theme resources for WallGDM.
//!
//! Uses `glib-compile-resources` to turn the `.gresource.xml` file
//! into a `.gresource` binary that can be installed as the login screen theme.

use crate::error::ThemeError;
use std::{
    path::{Path, PathBuf},
    process::Command,
};

/// Compile a `.gresource.xml` file into a `.gresource` binary.
///
/// # Parameters
/// - `gresource_xml`: Path to the XML file generated by [`generate_gresource_xml`].
///
/// # Returns
/// The path to the compiled `.gresource` binary.
///
/// # Errors
/// Returns `ThemeError` if compilation fails or the output file cannot be found.
///
/// # Notes
/// - The compilation itself does **not** require sudo, but installing the theme
///   (copying the compiled `.gresource`) usually does.
/// - Ensure that `glib-compile-resources` is installed on the system.
pub fn compile_theme(gresource_xml: &Path) -> Result<PathBuf, ThemeError> {
    log::debug!("Compiling theme resources from XML: {:?}", gresource_xml);

    let parent_dir = gresource_xml
        .parent()
        .ok_or(ThemeError::ThemeCompilationFailed)?;

    let status = Command::new("glib-compile-resources")
        .current_dir(parent_dir)
        .arg(gresource_xml)
        .status()
        .map_err(|_| ThemeError::CommandFailed("glib-compile-resources"))?;

    if !status.success() {
        return Err(ThemeError::ThemeCompilationFailed);
    }

    let compiled_resource = parent_dir.join("gnome-shell-theme.gresource");
    if !compiled_resource.exists() {
        return Err(ThemeError::ThemeCompilationFailed);
    }

    log::debug!(
        "Successfully compiled theme resource: {:?}",
        compiled_resource
    );

    Ok(compiled_resource)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_compile_theme_file_exists() {
        let tmp_dir = tempdir().expect("failed to create temp dir");
        let xml_path = tmp_dir.path().join("dummy.gresource.xml");

        // Create a minimal XML file (empty <gresources> is fine for test)
        fs::write(
            &xml_path,
            r#"<?xml version="1.0"?><gresources></gresources>"#,
        )
        .expect("failed to write dummy XML");

        // Should fail because glib-compile-resources cannot compile an empty resource
        let result = compile_theme(&xml_path);
        assert!(result.is_err());
    }
}
